const productsData = [
  {
    id: 1,
    name: "Premium Polo Shirt",
    category: "Menswear",
    fabric: "Single Jersey / Pique",
    gsm: "180-220",
    details: "Organic Cotton, 180-220 GSM",
    description: "Premium cotton pique polo shirt with a structured collar and reinforced placket. Engineered for comfort and durability across high-volume production runs.",
    image: "https://img.drz.lazcdn.com/static/bd/p/a821c829f953f33270baa0e663f012a7.jpg_960x960q80.jpg_.webp",
    featured: true,
    moq: "500 pcs",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Black", hex: "#000000" },
      { name: "White", hex: "#FFFFFF" },
      { name: "Navy", hex: "#1B2A4A" },
    ],
  },
  {
    id: 2,
    name: "Performance Leggings",
    category: "Active & Innerwear",
    fabric: "Interlock / Lycra Blend",
    gsm: "200-240",
    details: "Moisture-wicking, Four-way stretch",
    description: "High-performance compression leggings with moisture management and four-way stretch. Ideal for activewear and athleisure markets.",
    image: "https://www.buytshirtsonline.co.uk/images/womens-tridri-recycled-performance-leggings-3-4-length-p11960-384304_image.jpg",
    featured: false,
    moq: "300 pcs",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: [
      { name: "Charcoal", hex: "#36454F" },
      { name: "Black", hex: "#000000" },
    ],
  },
  {
    id: 3,
    name: "Structured Fashion Tee",
    category: "Womenswear",
    fabric: "Viscose / Elastane",
    gsm: "160-180",
    details: "High-density print compatible",
    description: "Structured viscose blend tee with a relaxed fit and premium hand-feel. Perfect for high-density printing and embellishment.",
    image: "https://buonitalianfashion.lu/cdn/shop/files/0040-2026.02.20-photo-catalogBIF2078.jpg?v=1772529432",
    featured: true,
    moq: "400 pcs",
    sizes: ["XS", "S", "M", "L"],
    colors: [
      { name: "Cream", hex: "#FFFDD0" },
      { name: "Sage", hex: "#9DC183" },
      { name: "Blush", hex: "#DE5D83" },
    ],
  },
  {
    id: 4,
    name: "Children's Nightwear Set",
    category: "Kids",
    fabric: "100% Rib Cotton",
    gsm: "140-160",
    details: "Hypoallergenic, Soft-touch finish",
    description: "Gentle rib cotton children's nightwear set with flatlock seams and tagless labels. Designed for sensitive skin and maximum comfort.",
    image: "https://www.petite-plume.com/cdn/shop/files/SPJPS_Pink_2_73198fd2-bd62-4f55-b49a-28fe315e71e7.jpg?v=1770410987",
    featured: false,
    moq: "600 pcs",
    sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y", "10-12Y"],
    colors: [
      { name: "Pink", hex: "#FFB6C1" },
      { name: "Lavender", hex: "#E6E6FA" },
    ],
  },
  {
    id: 5,
    name: "Technical Hoodie",
    category: "Menswear",
    fabric: "CVC Fleece",
    gsm: "300-340",
    details: "Brushed interior, Ribbed cuffs",
    description: "Heavyweight CVC fleece hoodie with brushed interior and kangaroo pocket. Engineered for warmth and structured silhouette.",
    image: "https://cdn.shopify.com/s/files/1/2415/8099/files/FINAL_0009_PRO-TECH_HOODIE_BLACK12_6f2a5ad7-fd01-497f-a511-253d4f0b8f48.jpg?v=1773254728",
    featured: true,
    moq: "300 pcs",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Black", hex: "#000000" },
      { name: "Heather Grey", hex: "#9E9E9E" },
    ],
  },
  {
    id: 6,
    name: "Ergonomic Boxer Briefs",
    category: "Active & Innerwear",
    fabric: "Modal / Spandex",
    gsm: "160-180",
    details: "Seamless construction, Flatlock seams",
    description: "Premium modal blend boxer briefs with ergonomic pouch design and seamless construction. Ultra-soft hand-feel for everyday comfort.",
    image: "https://m.media-amazon.com/images/I/717gK47yfpL._AC_UY1100_.jpg",
    featured: false,
    moq: "1000 pcs",
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Black", hex: "#000000" },
      { name: "Navy", hex: "#1B2A4A" },
      { name: "Grey", hex: "#808080" },
    ],
  },
  {
    id: 7,
    name: "Summer Floral Kurti",
    category: "Womenswear",
    fabric: "Cotton Voile",
    gsm: "100-120",
    details: "Block printed, Breathable weave",
    description: "Lightweight cotton voile kurti with hand block-printed floral motifs. Designed for warm-weather retail collections.",
    image: "https://res.cloudinary.com/dcdmktxtz/image/upload/v1768888316/samples/look-up.jpg",
    featured: true,
    moq: "500 pcs",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: [
      { name: "Indigo", hex: "#3F00FF" },
      { name: "Turmeric", hex: "#FFD300" },
    ],
  },
  {
    id: 8,
    name: "Men Linen Shirt",
    category: "Menswear",
    fabric: "100% Linen",
    gsm: "140-160",
    details: "Washed finish, Relaxed fit",
    description: "Premium European linen shirt with pre-washed softness and mother-of-pearl buttons. A staple for resort and casual wear lines.",
    image: "https://res.cloudinary.com/dcdmktxtz/image/upload/v1768888319/samples/woman-on-a-football-field.jpg",
    featured: false,
    moq: "300 pcs",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Natural", hex: "#F5F5DC" },
      { name: "Sky Blue", hex: "#87CEEB" },
    ],
  },
];

export default productsData;
